--
-- PostgreSQL database dump
--  how to ru: pehle ye wala database bnao :  createdb bs_db  than runn this : psql bs_db < schema.sql

\restrict 7pDt7rUMMsmjP5SOc9PdP5OsdSvCQbem3GMtuckt6si8CyRQ0akulbNTvYSrVY7

-- Dumped from database version 17.9 (Debian 17.9-0+deb13u1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apsokara_attendance; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_attendance (
    id bigint NOT NULL,
    date date NOT NULL,
    status character varying(10) NOT NULL,
    marked_by text NOT NULL,
    face_status character varying(20) NOT NULL,
    edit_count integer NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.apsokara_attendance OWNER TO sami_admin;

--
-- Name: apsokara_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_dailydiary; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_dailydiary (
    id bigint NOT NULL,
    student_class character varying(10) NOT NULL,
    section character varying(10) NOT NULL,
    wing character varying(10) NOT NULL,
    content text NOT NULL,
    date_posted date NOT NULL,
    attachments character varying(100),
    subject_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.apsokara_dailydiary OWNER TO sami_admin;

--
-- Name: apsokara_dailydiary_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_dailydiary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_dailydiary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_schoolnews; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_schoolnews (
    id bigint NOT NULL,
    content text NOT NULL,
    target_role character varying(50) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.apsokara_schoolnews OWNER TO sami_admin;

--
-- Name: apsokara_schoolnews_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_schoolnews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_schoolnews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_student; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_student (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    father_name character varying(100) NOT NULL,
    b_form character varying(20) NOT NULL,
    dob date NOT NULL,
    profile_pic character varying(100),
    student_class character varying(10) NOT NULL,
    student_section character varying(10) NOT NULL,
    wing character varying(10) NOT NULL,
    roll_number character varying(20) NOT NULL,
    nationality character varying(50) NOT NULL,
    province character varying(20) NOT NULL,
    religion character varying(20) NOT NULL,
    parents_phone character varying(15) NOT NULL,
    address text NOT NULL
);


ALTER TABLE public.apsokara_student OWNER TO sami_admin;

--
-- Name: apsokara_student_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_studentleave; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_studentleave (
    id bigint NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    reason text,
    status character varying(20) NOT NULL,
    attachment character varying(100),
    student_id bigint NOT NULL
);


ALTER TABLE public.apsokara_studentleave OWNER TO sami_admin;

--
-- Name: apsokara_studentleave_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_studentleave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_studentleave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_subject; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_subject (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.apsokara_subject OWNER TO sami_admin;

--
-- Name: apsokara_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_subjectassignment; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_subjectassignment (
    id bigint NOT NULL,
    student_class character varying(10) NOT NULL,
    section character varying(10) NOT NULL,
    wing character varying(10),
    subject_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.apsokara_subjectassignment OWNER TO sami_admin;

--
-- Name: apsokara_subjectassignment_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_subjectassignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_subjectassignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apsokara_teacher; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.apsokara_teacher (
    id bigint NOT NULL,
    full_name character varying(100) NOT NULL,
    father_name character varying(100) NOT NULL,
    cnic character varying(15) NOT NULL,
    dob date NOT NULL,
    religion character varying(20) NOT NULL,
    contact character varying(15) NOT NULL,
    address text NOT NULL,
    profile_pic character varying(100),
    is_class_teacher boolean NOT NULL,
    assigned_class character varying(10),
    assigned_section character varying(10),
    assigned_wing character varying(10) NOT NULL
);


ALTER TABLE public.apsokara_teacher OWNER TO sami_admin;

--
-- Name: apsokara_teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.apsokara_teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apsokara_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO sami_admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO sami_admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO sami_admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO sami_admin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO sami_admin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO sami_admin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO sami_admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO sami_admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO sami_admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: sami_admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: sami_admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO sami_admin;

--
-- Name: apsokara_attendance apsokara_attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_attendance
    ADD CONSTRAINT apsokara_attendance_pkey PRIMARY KEY (id);


--
-- Name: apsokara_dailydiary apsokara_dailydiary_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_dailydiary
    ADD CONSTRAINT apsokara_dailydiary_pkey PRIMARY KEY (id);


--
-- Name: apsokara_schoolnews apsokara_schoolnews_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_schoolnews
    ADD CONSTRAINT apsokara_schoolnews_pkey PRIMARY KEY (id);


--
-- Name: apsokara_student apsokara_student_b_form_key; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_student
    ADD CONSTRAINT apsokara_student_b_form_key UNIQUE (b_form);


--
-- Name: apsokara_student apsokara_student_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_student
    ADD CONSTRAINT apsokara_student_pkey PRIMARY KEY (id);


--
-- Name: apsokara_student apsokara_student_roll_number_key; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_student
    ADD CONSTRAINT apsokara_student_roll_number_key UNIQUE (roll_number);


--
-- Name: apsokara_studentleave apsokara_studentleave_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_studentleave
    ADD CONSTRAINT apsokara_studentleave_pkey PRIMARY KEY (id);


--
-- Name: apsokara_subject apsokara_subject_name_key; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_subject
    ADD CONSTRAINT apsokara_subject_name_key UNIQUE (name);


--
-- Name: apsokara_subject apsokara_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_subject
    ADD CONSTRAINT apsokara_subject_pkey PRIMARY KEY (id);


--
-- Name: apsokara_subjectassignment apsokara_subjectassignme_subject_id_student_class_2369cd83_uniq; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_subjectassignment
    ADD CONSTRAINT apsokara_subjectassignme_subject_id_student_class_2369cd83_uniq UNIQUE (subject_id, student_class, section, wing);


--
-- Name: apsokara_subjectassignment apsokara_subjectassignment_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_subjectassignment
    ADD CONSTRAINT apsokara_subjectassignment_pkey PRIMARY KEY (id);


--
-- Name: apsokara_teacher apsokara_teacher_cnic_key; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_teacher
    ADD CONSTRAINT apsokara_teacher_cnic_key UNIQUE (cnic);


--
-- Name: apsokara_teacher apsokara_teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_teacher
    ADD CONSTRAINT apsokara_teacher_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: apsokara_attendance_student_id_f60b30a7; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_attendance_student_id_f60b30a7 ON public.apsokara_attendance USING btree (student_id);


--
-- Name: apsokara_dailydiary_subject_id_52836257; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_dailydiary_subject_id_52836257 ON public.apsokara_dailydiary USING btree (subject_id);


--
-- Name: apsokara_dailydiary_teacher_id_9ba68570; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_dailydiary_teacher_id_9ba68570 ON public.apsokara_dailydiary USING btree (teacher_id);


--
-- Name: apsokara_student_b_form_649358d9_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_student_b_form_649358d9_like ON public.apsokara_student USING btree (b_form varchar_pattern_ops);


--
-- Name: apsokara_student_roll_number_0d9f0117_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_student_roll_number_0d9f0117_like ON public.apsokara_student USING btree (roll_number varchar_pattern_ops);


--
-- Name: apsokara_studentleave_student_id_000403c3; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_studentleave_student_id_000403c3 ON public.apsokara_studentleave USING btree (student_id);


--
-- Name: apsokara_subject_name_d09f8eda_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_subject_name_d09f8eda_like ON public.apsokara_subject USING btree (name varchar_pattern_ops);


--
-- Name: apsokara_subjectassignment_subject_id_04e6f632; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_subjectassignment_subject_id_04e6f632 ON public.apsokara_subjectassignment USING btree (subject_id);


--
-- Name: apsokara_subjectassignment_teacher_id_59a1ab0d; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_subjectassignment_teacher_id_59a1ab0d ON public.apsokara_subjectassignment USING btree (teacher_id);


--
-- Name: apsokara_teacher_cnic_be231539_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX apsokara_teacher_cnic_be231539_like ON public.apsokara_teacher USING btree (cnic varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: sami_admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: apsokara_attendance apsokara_attendance_student_id_f60b30a7_fk_apsokara_student_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_attendance
    ADD CONSTRAINT apsokara_attendance_student_id_f60b30a7_fk_apsokara_student_id FOREIGN KEY (student_id) REFERENCES public.apsokara_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apsokara_dailydiary apsokara_dailydiary_subject_id_52836257_fk_apsokara_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_dailydiary
    ADD CONSTRAINT apsokara_dailydiary_subject_id_52836257_fk_apsokara_subject_id FOREIGN KEY (subject_id) REFERENCES public.apsokara_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apsokara_dailydiary apsokara_dailydiary_teacher_id_9ba68570_fk_apsokara_teacher_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_dailydiary
    ADD CONSTRAINT apsokara_dailydiary_teacher_id_9ba68570_fk_apsokara_teacher_id FOREIGN KEY (teacher_id) REFERENCES public.apsokara_teacher(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apsokara_studentleave apsokara_studentleav_student_id_000403c3_fk_apsokara_; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_studentleave
    ADD CONSTRAINT apsokara_studentleav_student_id_000403c3_fk_apsokara_ FOREIGN KEY (student_id) REFERENCES public.apsokara_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apsokara_subjectassignment apsokara_subjectassi_subject_id_04e6f632_fk_apsokara_; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_subjectassignment
    ADD CONSTRAINT apsokara_subjectassi_subject_id_04e6f632_fk_apsokara_ FOREIGN KEY (subject_id) REFERENCES public.apsokara_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: apsokara_subjectassignment apsokara_subjectassi_teacher_id_59a1ab0d_fk_apsokara_; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.apsokara_subjectassignment
    ADD CONSTRAINT apsokara_subjectassi_teacher_id_59a1ab0d_fk_apsokara_ FOREIGN KEY (teacher_id) REFERENCES public.apsokara_teacher(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: sami_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 7pDt7rUMMsmjP5SOc9PdP5OsdSvCQbem3GMtuckt6si8CyRQ0akulbNTvYSrVY7

