PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO django_migrations VALUES(1,'contenttypes','0001_initial','2026-05-06 06:55:08.816353');
INSERT INTO django_migrations VALUES(2,'auth','0001_initial','2026-05-06 06:55:09.068462');
INSERT INTO django_migrations VALUES(3,'admin','0001_initial','2026-05-06 06:55:09.268664');
INSERT INTO django_migrations VALUES(4,'admin','0002_logentry_remove_auto_add','2026-05-06 06:55:09.356162');
INSERT INTO django_migrations VALUES(5,'admin','0003_logentry_add_action_flag_choices','2026-05-06 06:55:09.477464');
INSERT INTO django_migrations VALUES(6,'apsokara','0001_initial','2026-05-06 06:55:09.680008');
INSERT INTO django_migrations VALUES(7,'contenttypes','0002_remove_content_type_name','2026-05-06 06:55:09.797262');
INSERT INTO django_migrations VALUES(8,'auth','0002_alter_permission_name_max_length','2026-05-06 06:55:09.942104');
INSERT INTO django_migrations VALUES(9,'auth','0003_alter_user_email_max_length','2026-05-06 06:55:10.069466');
INSERT INTO django_migrations VALUES(10,'auth','0004_alter_user_username_opts','2026-05-06 06:55:10.199091');
INSERT INTO django_migrations VALUES(11,'auth','0005_alter_user_last_login_null','2026-05-06 06:55:10.284826');
INSERT INTO django_migrations VALUES(12,'auth','0006_require_contenttypes_0002','2026-05-06 06:55:10.368695');
INSERT INTO django_migrations VALUES(13,'auth','0007_alter_validators_add_error_messages','2026-05-06 06:55:10.446169');
INSERT INTO django_migrations VALUES(14,'auth','0008_alter_user_username_max_length','2026-05-06 06:55:10.528020');
INSERT INTO django_migrations VALUES(15,'auth','0009_alter_user_last_name_max_length','2026-05-06 06:55:10.635340');
INSERT INTO django_migrations VALUES(16,'auth','0010_alter_group_name_max_length','2026-05-06 06:55:10.734847');
INSERT INTO django_migrations VALUES(17,'auth','0011_update_proxy_permissions','2026-05-06 06:55:10.846921');
INSERT INTO django_migrations VALUES(18,'auth','0012_alter_user_first_name_max_length','2026-05-06 06:55:10.939551');
INSERT INTO django_migrations VALUES(19,'sessions','0001_initial','2026-05-06 06:55:11.137273');
INSERT INTO django_migrations VALUES(20,'super_admin','0001_initial','2026-05-06 06:55:11.214884');
INSERT INTO django_migrations VALUES(21,'super_admin','0002_schoolclient_logo','2026-05-06 06:55:11.270770');
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "apsokara_schoolnews" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content" text NOT NULL, "target_role" varchar(50) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "is_active" bool NOT NULL, "created_at" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "apsokara_student" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "full_name" varchar(100) NOT NULL, "father_name" varchar(100) NOT NULL, "b_form" varchar(20) NOT NULL UNIQUE, "dob" date NOT NULL, "student_class" varchar(10) NOT NULL, "student_section" varchar(10) NOT NULL, "wing" varchar(10) NOT NULL, "roll_number" varchar(20) NOT NULL UNIQUE, "nationality" varchar(50) NOT NULL, "province" varchar(20) NOT NULL, "religion" varchar(20) NOT NULL, "parents_phone" varchar(15) NOT NULL, "address" text NOT NULL);
CREATE TABLE IF NOT EXISTS "apsokara_subject" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "apsokara_teacher" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "full_name" varchar(100) NOT NULL, "father_name" varchar(100) NOT NULL, "cnic" varchar(15) NOT NULL UNIQUE, "dob" date NOT NULL, "religion" varchar(20) NOT NULL, "contact" varchar(15) NOT NULL, "address" text NOT NULL, "is_class_teacher" bool NOT NULL, "assigned_class" varchar(10) NULL, "assigned_section" varchar(10) NULL, "assigned_wing" varchar(10) NOT NULL);
CREATE TABLE IF NOT EXISTS "apsokara_attendance" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "status" varchar(10) NOT NULL, "marked_by" text NOT NULL, "student_id" bigint NOT NULL REFERENCES "apsokara_student" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "apsokara_studentleave" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_date" date NOT NULL, "to_date" date NOT NULL, "student_id" bigint NOT NULL REFERENCES "apsokara_student" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "apsokara_subjectassignment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "student_class" varchar(10) NOT NULL, "section" varchar(10) NOT NULL, "wing" varchar(10) NOT NULL, "subject_id" bigint NOT NULL REFERENCES "apsokara_subject" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" bigint NOT NULL REFERENCES "apsokara_teacher" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO django_content_type VALUES(1,'admin','logentry');
INSERT INTO django_content_type VALUES(2,'auth','group');
INSERT INTO django_content_type VALUES(3,'auth','permission');
INSERT INTO django_content_type VALUES(4,'auth','user');
INSERT INTO django_content_type VALUES(5,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(6,'sessions','session');
INSERT INTO django_content_type VALUES(7,'apsokara','attendance');
INSERT INTO django_content_type VALUES(8,'apsokara','schoolnews');
INSERT INTO django_content_type VALUES(9,'apsokara','student');
INSERT INTO django_content_type VALUES(10,'apsokara','studentleave');
INSERT INTO django_content_type VALUES(11,'apsokara','subject');
INSERT INTO django_content_type VALUES(12,'apsokara','subjectassignment');
INSERT INTO django_content_type VALUES(13,'apsokara','teacher');
INSERT INTO django_content_type VALUES(14,'super_admin','schoolclient');
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO auth_permission VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(5,3,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(6,3,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(8,3,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(9,2,'add_group','Can add group');
INSERT INTO auth_permission VALUES(10,2,'change_group','Can change group');
INSERT INTO auth_permission VALUES(11,2,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(12,2,'view_group','Can view group');
INSERT INTO auth_permission VALUES(13,4,'add_user','Can add user');
INSERT INTO auth_permission VALUES(14,4,'change_user','Can change user');
INSERT INTO auth_permission VALUES(15,4,'delete_user','Can delete user');
INSERT INTO auth_permission VALUES(16,4,'view_user','Can view user');
INSERT INTO auth_permission VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(21,6,'add_session','Can add session');
INSERT INTO auth_permission VALUES(22,6,'change_session','Can change session');
INSERT INTO auth_permission VALUES(23,6,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(24,6,'view_session','Can view session');
INSERT INTO auth_permission VALUES(25,8,'add_schoolnews','Can add school news');
INSERT INTO auth_permission VALUES(26,8,'change_schoolnews','Can change school news');
INSERT INTO auth_permission VALUES(27,8,'delete_schoolnews','Can delete school news');
INSERT INTO auth_permission VALUES(28,8,'view_schoolnews','Can view school news');
INSERT INTO auth_permission VALUES(29,9,'add_student','Can add student');
INSERT INTO auth_permission VALUES(30,9,'change_student','Can change student');
INSERT INTO auth_permission VALUES(31,9,'delete_student','Can delete student');
INSERT INTO auth_permission VALUES(32,9,'view_student','Can view student');
INSERT INTO auth_permission VALUES(33,11,'add_subject','Can add subject');
INSERT INTO auth_permission VALUES(34,11,'change_subject','Can change subject');
INSERT INTO auth_permission VALUES(35,11,'delete_subject','Can delete subject');
INSERT INTO auth_permission VALUES(36,11,'view_subject','Can view subject');
INSERT INTO auth_permission VALUES(37,13,'add_teacher','Can add teacher');
INSERT INTO auth_permission VALUES(38,13,'change_teacher','Can change teacher');
INSERT INTO auth_permission VALUES(39,13,'delete_teacher','Can delete teacher');
INSERT INTO auth_permission VALUES(40,13,'view_teacher','Can view teacher');
INSERT INTO auth_permission VALUES(41,7,'add_attendance','Can add attendance');
INSERT INTO auth_permission VALUES(42,7,'change_attendance','Can change attendance');
INSERT INTO auth_permission VALUES(43,7,'delete_attendance','Can delete attendance');
INSERT INTO auth_permission VALUES(44,7,'view_attendance','Can view attendance');
INSERT INTO auth_permission VALUES(45,10,'add_studentleave','Can add student leave');
INSERT INTO auth_permission VALUES(46,10,'change_studentleave','Can change student leave');
INSERT INTO auth_permission VALUES(47,10,'delete_studentleave','Can delete student leave');
INSERT INTO auth_permission VALUES(48,10,'view_studentleave','Can view student leave');
INSERT INTO auth_permission VALUES(49,12,'add_subjectassignment','Can add subject assignment');
INSERT INTO auth_permission VALUES(50,12,'change_subjectassignment','Can change subject assignment');
INSERT INTO auth_permission VALUES(51,12,'delete_subjectassignment','Can delete subject assignment');
INSERT INTO auth_permission VALUES(52,12,'view_subjectassignment','Can view subject assignment');
INSERT INTO auth_permission VALUES(53,14,'add_schoolclient','Can add school client');
INSERT INTO auth_permission VALUES(54,14,'change_schoolclient','Can change school client');
INSERT INTO auth_permission VALUES(55,14,'delete_schoolclient','Can delete school client');
INSERT INTO auth_permission VALUES(56,14,'view_schoolclient','Can view school client');
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
INSERT INTO auth_user VALUES(1,'pbkdf2_sha256$1200000$OIEQItLErVUcSc00BciPsU$wsmc+Q8Jyg9P58LuLPTfqXJw+YacCp5rLcEglllowDA=',NULL,1,'s','','admin@sss.com',1,1,'2026-05-06 06:55:12.627758','');
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('django_migrations',21);
INSERT INTO sqlite_sequence VALUES('django_admin_log',0);
INSERT INTO sqlite_sequence VALUES('django_content_type',14);
INSERT INTO sqlite_sequence VALUES('auth_permission',56);
INSERT INTO sqlite_sequence VALUES('auth_group',0);
INSERT INTO sqlite_sequence VALUES('auth_user',1);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "apsokara_attendance_student_id_f60b30a7" ON "apsokara_attendance" ("student_id");
CREATE INDEX "apsokara_studentleave_student_id_000403c3" ON "apsokara_studentleave" ("student_id");
CREATE UNIQUE INDEX "apsokara_subjectassignment_subject_id_student_class_section_wing_2369cd83_uniq" ON "apsokara_subjectassignment" ("subject_id", "student_class", "section", "wing");
CREATE INDEX "apsokara_subjectassignment_subject_id_04e6f632" ON "apsokara_subjectassignment" ("subject_id");
CREATE INDEX "apsokara_subjectassignment_teacher_id_59a1ab0d" ON "apsokara_subjectassignment" ("teacher_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;
