# Generated by Django 6.0 on 2026-01-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Mid Term 2025', max_length=100)),
                ('session_year', models.CharField(default='2024-25', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Check to open mark entry for teachers')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Window',
                'verbose_name_plural': 'Exam Windows',
            },
        ),
        migrations.CreateModel(
            name='SchoolNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('wing', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=10)),
                ('student_class', models.CharField(blank=True, max_length=20, null=True)),
                ('student_section', models.CharField(blank=True, max_length=20, null=True)),
                ('session_year', models.CharField(default='2024-25', max_length=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_phone', models.CharField(default='03000000000', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='N/A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('wing', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=10)),
                ('incharge_class', models.CharField(blank=True, max_length=20, null=True)),
                ('incharge_section', models.CharField(blank=True, max_length=20, null=True)),
                ('is_class_incharge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('edit_count', models.IntegerField(default=0)),
                ('wing', models.CharField(blank=True, max_length=10, null=True)),
                ('student_class', models.CharField(blank=True, max_length=20, null=True)),
                ('student_section', models.CharField(blank=True, max_length=20, null=True)),
                ('session_year', models.CharField(default='2024-25', max_length=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolArchive',
            fields=[
            ],
            options={
                'verbose_name': 'Digital Archive Vault',
                'verbose_name_plural': 'Digital Archive Vaults',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apsokara.student',),
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
            ],
            options={
                'verbose_name': '🚀 Student Promotion Console',
                'verbose_name_plural': '🚀 Student Promotion Console',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apsokara.student',),
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('wing', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('wing', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.teacher')),
            ],
        ),
    ]
