# Generated by Django 4.2.28 on 2026-05-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_schoolclient_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclient',
            name='is_co_ed',
            field=models.BooleanField(default=False),
        ),
    ]
