# Generated by Django 6.0.4 on 2026-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_schoolclient_is_co_ed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclient',
            name='is_co_ed',
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='school_type',
            field=models.CharField(choices=[('wing', 'Wing Based'), ('co', 'Co-Education')], default='wing', max_length=10),
        ),
    ]
