# Generated by Django 6.0.4 on 2026-05-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_remove_schoolclient_is_co_ed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclient',
            name='school_type',
        ),
    ]
