# Generated by Django 6.0.4 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_remove_schoolclient_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclient',
            name='school_type',
            field=models.CharField(choices=[('co-ed', 'Co-Education'), ('wing-based', 'Wing Based (Boys/Girls)')], default='co-ed', max_length=20),
        ),
    ]
