# Generated by Django 6.0.1 on 2026-01-30 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('b_form', models.CharField(max_length=20, unique=True, verbose_name='B-Form Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('student_class', models.CharField(max_length=10)),
                ('student_section', models.CharField(max_length=10)),
                ('wing', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('KPK', 'KPK'), ('Balochistan', 'Balochistan'), ('Gilgit', 'Gilgit'), ('AJK', 'AJK')], default='Punjab', max_length=20)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Other', 'Other')], default='Islam', max_length=20)),
                ('parents_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Subject Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Other', 'Other')], default='Islam', max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('assigned_class', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned_section', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned_wing', models.CharField(choices=[('None', 'None'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('wing', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='apsokara.teacher')),
            ],
            options={
                'unique_together': {('subject', 'student_class', 'section', 'wing')},
            },
        ),
    ]
