# Generated by Django 6.0.1 on 2026-01-30 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='News Content')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.TextField(default='Unknown'),
        ),
    ]
