# Generated by Django 6.0.4 on 2026-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wing',
            field=models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='wing',
            field=models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_wing',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='None', max_length=10, null=True),
        ),
    ]
