# Generated by Django 6.0.4 on 2026-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0002_exam_feestructure_schoolfeesettings_examresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeesettings',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
    ]
