# Generated by Django 6.0.4 on 2026-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0002_alter_student_wing_alter_subjectassignment_wing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wing',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='wing',
            field=models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_wing',
            field=models.CharField(choices=[('None', 'None'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='None', max_length=10),
        ),
    ]
