# Generated by Django 6.0.1 on 2026-01-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0002_schoolnews_attendance_marked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnews',
            name='content',
            field=models.TextField(),
        ),
    ]
