# Generated by Django 6.0.1 on 2026-03-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0002_academicsession_classlock_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('students_total', models.PositiveIntegerField()),
                ('students_passed', models.PositiveIntegerField()),
                ('students_failed', models.PositiveIntegerField()),
                ('students_graduated', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apsokara.academicsession')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_settings', to='apsokara.academicsession')),
                ('target_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_for_promo', to='apsokara.academicsession')),
            ],
        ),
    ]
