# Generated by Django 6.0.4 on 2026-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0003_schoolfeesettings_grace_period_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=20)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('auto', 'Auto Cron'), ('manual', 'Manual')], max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('students_processed', models.IntegerField()),
                ('records_created', models.IntegerField()),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='grace_period_days',
        ),
        migrations.AddField(
            model_name='feerecord',
            name='waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='waived_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override monthly fee if set', max_digits=10, null=True),
        ),
    ]
