# Generated by Django 6.0.1 on 2026-01-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0003_alter_schoolnews_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnews',
            name='target_role',
            field=models.CharField(choices=[('All', 'All'), ('Student', 'Student'), ('Class Teacher', 'Class Teacher'), ('Subject Teacher', 'Subject Teacher')], default='All', max_length=50),
        ),
    ]
