# Generated by Django 6.0.1 on 2026-04-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0003_promotionaudit_promotionsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlock',
            name='session',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='promotionaudit',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='PromotionSettings',
        ),
        migrations.DeleteModel(
            name='ClassLock',
        ),
        migrations.DeleteModel(
            name='AcademicSession',
        ),
        migrations.DeleteModel(
            name='PromotionAudit',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
