# Generated by Django 6.0.1 on 2026-01-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0004_schoolnews_target_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnews',
            name='target_role',
            field=models.CharField(default='All', max_length=50),
        ),
    ]
