# Generated by fee_upgrade_patcher
from django.db import migrations, models
import django.core.validators
from decimal import Decimal

class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0004_auditlog_feegenerationlog_and_more'),
    ]

    operations = [
        # Add new fields to SchoolFeeSettings
        migrations.AddField(
            model_name='schoolfeesettings',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='max_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='penalty_recurrence',
            field=models.CharField(choices=[('once', 'One-time'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='pro_rata_new_student',
            field=models.CharField(choices=[('full', 'Full Month'), ('half', 'Half Month'), ('daily', 'Daily')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='pro_rata_leaving',
            field=models.CharField(choices=[('full', 'Full Month'), ('half', 'Half Month'), ('daily', 'Daily')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='min_partial_month_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='send_email_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='reminder_days_before',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='penalty_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='last_penalty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='pro_rata_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
