# Generated by Django 6.0.1 on 2026-01-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0005_alter_schoolnews_target_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolnews',
            name='target_role',
        ),
    ]
