# Generated by Django 6.0.4 on 2026-05-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0005_fee_upgrade_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='last_penalty_date',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='penalty_applied',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='pro_rata_factor',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='grace_period_days',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='max_penalty',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='min_partial_month_fee',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='penalty_amount',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='penalty_recurrence',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='penalty_type',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='pro_rata_leaving',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='pro_rata_new_student',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='reminder_days_before',
        ),
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='send_email_reminders',
        ),
    ]
