# Generated by Django 6.0.4 on 2026-05-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0006_remove_feerecord_last_penalty_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='max_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum penalty (0 = no max)', max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='notify_email',
            field=models.BooleanField(default=False, help_text='Send email reminders to defaulters'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty amount or percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='pro_rata_type',
            field=models.CharField(choices=[('full', 'Full Month'), ('half', 'Half Month'), ('daily', 'Daily')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='max_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum penalty (0 = no max)', max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='notify_email',
            field=models.BooleanField(default=False, help_text='Send email reminders to defaulters'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty amount or percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='pro_rata_type',
            field=models.CharField(choices=[('full', 'Full Month'), ('half', 'Half Month'), ('daily', 'Daily')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='grace_period_days',
            field=models.IntegerField(default=0, help_text='Days after due date before penalty applies'),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='max_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum penalty (0 = no max)', max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='notify_email',
            field=models.BooleanField(default=False, help_text='Send email reminders to defaulters'),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty amount or percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolfeesettings',
            name='pro_rata_type',
            field=models.CharField(choices=[('full', 'Full Month'), ('half', 'Half Month'), ('daily', 'Daily')], default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='LateFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_logs', to='apsokara.feerecord')),
            ],
        ),
    ]
