# Generated by Django 6.0.1 on 2026-02-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0007_schoolnews_target_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolNews',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by',
        ),
    ]
