# Generated by fix_father_cnic_migration.py
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('apsokara', '0007_feerecord_grace_period_days_feerecord_max_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(default='', max_length=15, verbose_name='Father CNIC', help_text="Father's CNIC for family payments"),
            preserve_default=False,
        ),
    ]
